# --------------------------------------------------------------------------------------------------
#                               IMAGE PARAMETERS
# --------------------------------------------------------------------------------------------------
image:
  repository: "goit-dev-ops/django-app"
  tag: "latest"
  pullPolicy: "Always"

# --------------------------------------------------------------------------------------------------
#                              REPLICAS PARAMETERS
# --------------------------------------------------------------------------------------------------
replicaCount: 1

# --------------------------------------------------------------------------------------------------
#                               SERVICE PARAMETERS
# --------------------------------------------------------------------------------------------------
service:
  type: "LoadBalancer"
  port: 80
  targetPort: 8000

# --------------------------------------------------------------------------------------------------
#                               Horizontal Pod Autoscaler PARAMETERS
# --------------------------------------------------------------------------------------------------
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80

# --------------------------------------------------------------------------------------------------
#                               CONTAINER PARAMETERS
# --------------------------------------------------------------------------------------------------
container:
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

# --------------------------------------------------------------------------------------------------
#                               ENVIRONMENT VARIABLES
# --------------------------------------------------------------------------------------------------
config:
  DJANGO_SETTINGS_MODULE: "app.settings"
  DJANGO_ALLOWED_HOSTS: "*"
  DEBUG: "False"
  DATABASE_ENGINE: "django.db.backends.postgresql"
  DATABASE_HOST: "db"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "django_db"
  DATABASE_USER: "django_user"
  DATABASE_PASSWORD: "django_password"
