apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}-django
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.secret.databasePassword | required "secret.databasePassword is required" | quote }}
